### ISSUE TITLE
Error loading script: xyz_grid_support.py

### ISSUE THREAD

**Issue by neartspb** [Mikubill/sd-webui-controlnet#306]
this is today after the update

![errort_1](https://user-images.githubusercontent.com/32602340/220795938-6f7cdd15-3958-4eaf-8f69-41de6ef56dc9.jpg)

uninstalling and reinstalling did not help

**Comment by Mikubill** [comment]
Maybe fixed by https://github.com/Mikubill/sd-webui-controlnet/commit/ecad77ed65dac0dd51072cedaea5b7a7dfe7c795

**Comment by neartspb** [comment]
**after last update**
******************************************
Restarting UI...
Error loading script: xyz_grid_support.py
Traceback (most recent call last):
  File "C:\Users\kio\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\kio\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\kio\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\xyz_grid_support.py", line 118, in <module>
    add_axis_options(xyz_grid)
  File "C:\Users\kio\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\xyz_grid_support.py", line 102, in add_axis_options
    AxisOption("[ControlNet] Model", str, apply_field("control_net_model"), choices=choices_model, confirm=confirm_model, cost=0.9),
  File "C:\Users\kio\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\xyz_grid_support.py", line 37, in __new__
    this = super().__new__(xyz_grid.AxisOption)
TypeError: AxisOption.__new__() missing 5 required positional arguments: 'label', 'type', 'apply', 'format_value', and 'confirm'
******************************************
**python: 3.10.10  •  torch: 1.13.1+cu117  •  xformers: 0.0.16rc425  •  gradio: 3.16.2**
*****************************************
Thanks for your work
maybe this will help you

**Comment by aiton-sd** [comment]
This error is caused by an old version of WebUI.
In the current WebUI, AxisOption is defined as a class with three mandatory attributes.
However, in the old WebUI, it is defined as a namedtuple with 4-6 attributes.
Resolving this issue can be difficult, so please update the WebUI.

**Comment by neartspb** [comment]
Should I update stable-diffusion-webui ?
I did this but the error remains.
******************************
Or should I update Gradio?
I don't know how to update Gradio....

**Comment by neartspb** [comment]
Copying via zip archive to the old directory did not help!!!
But I installed "stable-diffusion-webui" to a new directory through
  
git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git

And everything started without errors!
You are a god !
from my heart thank you so much !
