### ISSUE TITLE
[Bug]:  ERROR

### ISSUE THREAD

**Issue by demirklvc** [Mikubill/sd-webui-controlnet#446]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

<img width="1440" alt="Bildschirmfoto 2023-03-02 um 00 23 13" src="https://user-images.githubusercontent.com/78754525/222289477-1adb42c0-8ecd-4565-83aa-f148121bdb1c.png">

Updated and from then on Error.

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...
-

### What should have happened?

work

### Commit where the problem happens

webui: 
controlnet: 
ö

### Command Line Arguments

```Shell
.
```

### Console logs

```Shell
ä
```

### Additional information

l

**Comment by Dragalur98** [comment]
I get the same error. ControlNet does not want to work. A clean reinstallation of the extension and models also did not solve the error.

![5](https://user-images.githubusercontent.com/93353660/222313141-e1c6a506-47ed-4e5e-bc0e-fec28743924e.png)

**Comment by ljleb** [comment]
> I get the same error. ControlNet does not want to work. A clean reinstallation of the extension and models also did not solve the error.

Can you try putting your sd folder in a path that does not contain spaces? you have double backslashes `\\` instead of single `\` which seems to be responsible for the error in your case.

**Comment by Peter00519** [comment]
> I get the same error. ControlNet does not want to work. A clean reinstallation of the extension and models also did not solve the error.
> 
> ![5](https://user-images.githubusercontent.com/93353660/222313141-e1c6a506-47ed-4e5e-bc0e-fec28743924e.png)

I have same error.
The problem is update and change the default path.
So go to setting > ControlNet
![image](https://user-images.githubusercontent.com/126740592/222318764-082992a2-37e6-43b5-a7d4-d5831f6029d2.png)
Correct this two path.

**Comment by Dragalur98** [comment]
> Can you try putting your sd folder in a path that does not contain spaces? you have double backslashes `\\` instead of single `\` which seems to be responsible for the error in your case.
> 
> Also maybe check your config defaults to see if the path has double backslashes there. (it should only contain single backslashes)

My folder path has only one backslashes in it. The path to the folder is absolutely correct and there should be no problem with it. I tried installing controlnet before the last fix controlnet.py script and the problem is solved, control net fully works. The problem is in the last update of the controlnet.py script. [https://github.com/Mikubill/sd-webui-controlnet/tree/65b06db0bca52e5bf689e54388f72a97ef07b277](url)

![Screenshot_2](https://user-images.githubusercontent.com/93353660/222319171-667ee463-fbb9-495d-a32f-cc79124886df.png)

**Comment by Dragalur98** [comment]
> > I get the same error. ControlNet does not want to work. A clean reinstallation of the extension and models also did not solve the error.
> > ![5](https://user-images.githubusercontent.com/93353660/222313141-e1c6a506-47ed-4e5e-bc0e-fec28743924e.png)
> 
> I have same error. The problem is update and change the default path. So go to setting > ControlNet ![image](https://user-images.githubusercontent.com/126740592/222318764-082992a2-37e6-43b5-a7d4-d5831f6029d2.png) Correct this two path.

Thanks for the way to fix the error! I'll stay with the ControlNet version until the last update for now, since everything works for me. I'll wait until **Mikubill** fixes the bug.

**Comment by Mikubill** [comment]
fixed in https://github.com/Mikubill/sd-webui-controlnet/commit/9b19c63e9872e3dc059c07a592bbe83250e8ce79

**Comment by JamesLogan2KB** [comment]
> > I get the same error. ControlNet does not want to work. A clean reinstallation of the extension and models also did not solve the error.
> > ![5](https://user-images.githubusercontent.com/93353660/222313141-e1c6a506-47ed-4e5e-bc0e-fec28743924e.png)
> 
> I have same error. The problem is update and change the default path. So go to setting > ControlNet ![image](https://user-images.githubusercontent.com/126740592/222318764-082992a2-37e6-43b5-a7d4-d5831f6029d2.png) Correct this two path.

This does not solve the problem. How to solve this problem?

**Comment by ivever2** [comment]
I finally found the problem, it was because (controlnet) and (segment-anything) conflicted, after closing (segment-anything), everything worked fine.

**Comment by Piscabo** [comment]
> I finally found the problem, it was because (controlnet) and (segment-anything) conflicted, after closing (segment-anything), everything worked fine.

What is 'segment anything'? Where do I find it to disable it? I have tried all the fixes I could find and still get the error using 2.1 models.

**Comment by AModestMouse** [comment]
This error appears to be back in the most recent commit 

![error](https://github.com/Mikubill/sd-webui-controlnet/assets/138523364/13c27408-cf75-4738-b468-8319bd36478d)
